/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rgupta; 

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Flashcard flashcard = new Flashcard("Apple", "https://www.bhg.co.at/wp-content/uploads/2018/05/Mango.jpg");
    }
}
