/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rgupta;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Einige Beispiel-Wort-Bild-Paare erstellen
        ArrayList<Flashcard> flashcards = new ArrayList<>();
        flashcards.add(new Flashcard("Dog",
                "https://upload.wikimedia.org/wikipedia/commons/d/d5/Retriever_in_water.jpg"));
        flashcards.add(new Flashcard("Cat",
                "https://i.natgeofe.com/n/548467d8-c5f1-4551-9f58-6817a8d2c45e/NationalGeographic_2572187.jpg?w=718&h=479"));
        flashcards.add(new Flashcard("Bird",
                "https://upload.wikimedia.org/wikipedia/commons/4/45/Eopsaltria_australis_-_Mogo_Campground.jpg"));

        // Statistiken initialisieren
        Statistics statistics = new Statistics();

        // Coach und View erstellen
        Coach coach = new Coach(statistics, flashcards);
        CoachView view = new CoachView();

        // Controller starten
        new CoachController(view, coach);
    }
}
